version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
build:
  project: source/play.sln
  verbosity: minimal
artifacts:
- path: source\Release\*.exe
  name: win32
- path: source\Release\*.dll
  name: win32
- path: dependencies\x86\*.dll
  name: win32
- path: source\x64\Release\*.dll
  name: win64
- path: source\x64\Release\*.exe
  name: win64
- path: dependencies\x64\*.dll
  name: win64